//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StructuredCablingStudio.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StructuredCablingStudio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 85.
        /// </summary>
        internal static string CalculateDTO_MaxPermanentLink_StandartValue {
            get {
                return ResourceManager.GetString("CalculateDTO.MaxPermanentLink.StandartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25.
        /// </summary>
        internal static string CalculateDTO_MinPermanentLink_StandartValue {
            get {
                return ResourceManager.GetString("CalculateDTO.MinPermanentLink.StandartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string CalculateDTO_NumberOfPorts_StandartValue {
            get {
                return ResourceManager.GetString("CalculateDTO.NumberOfPorts.StandartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string CalculateDTO_NumberOfWorkplaces_StandartValue {
            get {
                return ResourceManager.GetString("CalculateDTO.NumberOfWorkplaces.StandartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 305.
        /// </summary>
        internal static string ConfigurationCalculateParameters_CableHankMeterage_StandartValue {
            get {
                return ResourceManager.GetString("ConfigurationCalculateParameters.CableHankMeterage.StandartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string ConfigurationCalculateParameters_IsCableHankMeterageAvailability_StandartValue {
            get {
                return ResourceManager.GetString("ConfigurationCalculateParameters.IsCableHankMeterageAvailability.StandartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string StructuredCablingStudioParameters_IsAnArbitraryNumberOfPorts_StandartValue {
            get {
                return ResourceManager.GetString("StructuredCablingStudioParameters.IsAnArbitraryNumberOfPorts.StandartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string StructuredCablingStudioParameters_IsRecommendationsAvailability_StandartValue {
            get {
                return ResourceManager.GetString("StructuredCablingStudioParameters.IsRecommendationsAvailability.StandartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string StructuredCablingStudioParameters_IsStrictComplianceWithTheStandart_StandartValue {
            get {
                return ResourceManager.GetString("StructuredCablingStudioParameters.IsStrictComplianceWithTheStandart.StandartValue" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to true.
        /// </summary>
        internal static string StructuredCablingStudioParameters_IsTechnologicalReserveAvailability_StandartValue {
            get {
                return ResourceManager.GetString("StructuredCablingStudioParameters.IsTechnologicalReserveAvailability.StandartValu" +
                        "e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FastEthernet,GigabitBASE_T.
        /// </summary>
        internal static string StructuredCablingStudioParameters_RecommendationsArguments_ConnectionInterfaces_StandartValue {
            get {
                return ResourceManager.GetString("StructuredCablingStudioParameters.RecommendationsArguments.ConnectionInterfaces.S" +
                        "tandartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSZH.
        /// </summary>
        internal static string StructuredCablingStudioParameters_RecommendationsArguments_IsolationMaterial_StandartValue {
            get {
                return ResourceManager.GetString("StructuredCablingStudioParameters.RecommendationsArguments.IsolationMaterial.Stan" +
                        "dartValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor.
        /// </summary>
        internal static string StructuredCablingStudioParameters_RecommendationsArguments_IsolationType_StandartValue {
            get {
                return ResourceManager.GetString("StructuredCablingStudioParameters.RecommendationsArguments.IsolationType.Standart" +
                        "Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTP.
        /// </summary>
        internal static string StructuredCablingStudioParameters_RecommendationsArguments_ShieldedType_StandartValue {
            get {
                return ResourceManager.GetString("StructuredCablingStudioParameters.RecommendationsArguments.ShieldedType.StandartV" +
                        "alue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.10.
        /// </summary>
        internal static string StructuredCablingStudioParameters_TechnologicalReserve_StandartValue {
            get {
                return ResourceManager.GetString("StructuredCablingStudioParameters.TechnologicalReserve.StandartValue", resourceCulture);
            }
        }
    }
}
